###################################################
# This creates and stands up the development
# docker container. Depends on the Dockerfile and
# docker-start.sh files.
###################################################

services:
  actual-development:
    build: .
    image: actual-development
    environment:
      - HTTPS
    ports:
      - '5006:5006'
    volumes:
      - '.:/app'
    restart: 'unless-stopped'

